name: Docker Build and Push
on:
  push:
#      branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docker:
    name: Docker Build and Push
    runs-on: ubuntu-latest
    steps:
      - name: Get branch name (merge)
        if: github.event_name != 'pull_request'
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV

      - name: Replace master/main Branch Names with latest
        if: env.BRANCH_NAME == 'main' || env.BRANCH_NAME == 'master'
        shell: bash
        run: echo "BRANCH_NAME=latest" >> $GITHUB_ENV

      - name: Check value of env.BRANCH_NAME
        shell: bash
        run: echo ${{ env.BRANCH_NAME }}

      - uses: actions/checkout@v2
        name: Checkout Repository

      - uses: whoan/docker-build-with-cache-action@v5
        name: Build, Cache and Push Docker Image
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}

          image_tag: ${{ env.BRANCH_NAME }}
          image_name: ${{ secrets.DOCKER_REPOSITORY }}
#           cache: true
